# Site settings
name: Neel Patel
title: Neel Patel | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://ineelpatel.com
baseurl: ''
email: hello@ineelpatel.com
cover: https://ineelpatel.github.io/portfolio/img/og.png
logo: https://ineelpatel.github.io/portfolio/img/emojis/technologist.png
resume: https://ineelpatel.github.io/portfolio/resume.pdf
social:
  - title: email
    url: mailto:hello@ineelpatel.com
  - title: twitter
    url: https://twitter.com/ineelpatel
  - title: instagram
    url: https://instagram.com/ineelpatel_
  - title: github
    url: https://github.com/ineelpatel
  - title: linkedin
    url: https://www.linkedin.com/in/ineelpatel

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
